// Auto-generated from Excel export — one-time historical labs import data
export const labsImportData = [
  {
    "examDate": "2021-06-01",
    "department": "المختبر",
    "category": "تخثر الدم",
    "label": "النسبة المعيارية الدولية INR",
    "code": "inr",
    "valueText": "0.91",
    "numericValue": 0.91,
    "unit": null,
    "referenceRange": "0.80–1.20",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20210601-coag",
    "physician": "غير مذكور في لقطة النتيجة",
    "facility": "غير مذكورة في التقرير",
    "source": "WhatsAppImage2026-08-28at1.01.14PM.jpeg",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2021-06-01",
    "department": "المختبر",
    "category": "تخثر الدم",
    "label": "زمن البروثرومبين PT",
    "code": "pt",
    "valueText": "12.30",
    "numericValue": 12.3,
    "unit": "ثانية",
    "referenceRange": "12.00–15.00",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20210601-coag",
    "physician": "غير مذكور في لقطة النتيجة",
    "facility": "غير مذكورة في التقرير",
    "source": "WhatsAppImage2026-08-28at1.01.14PM.jpeg",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2021-06-01",
    "department": "المختبر",
    "category": "تخثر الدم",
    "label": "زمن الثرومبوبلاستين الجزئي APTT",
    "code": "aptt",
    "valueText": "31",
    "numericValue": 31,
    "unit": "ثانية",
    "referenceRange": "26–34",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20210601-coag",
    "physician": "غير مذكور في لقطة النتيجة",
    "facility": "غير مذكورة في التقرير",
    "source": "WhatsAppImage2026-08-28at1.01.14PM.jpeg",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الصفائح الدموية",
    "code": "platelets",
    "valueText": "194",
    "numericValue": 194,
    "unit": "10^3/µL",
    "referenceRange": "140–400",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الهيماتوكريت",
    "code": "hematocrit",
    "valueText": "28.4",
    "numericValue": 28.4,
    "unit": "%",
    "referenceRange": "35–48",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الهيموغلوبين",
    "code": "hemoglobin",
    "valueText": "10.1",
    "numericValue": 10.1,
    "unit": "g/dL",
    "referenceRange": "11–16",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "تباين حجم الكريات RDW",
    "code": "rdw",
    "valueText": "17.3",
    "numericValue": 17.3,
    "unit": "%",
    "referenceRange": "11.5–16.5",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "تركيز هيموغلوبين الكرية MCHC",
    "code": "mchc",
    "valueText": "35.6",
    "numericValue": 35.6,
    "unit": "g/dL",
    "referenceRange": "32–36",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "كريات الدم البيضاء",
    "code": "wbc",
    "valueText": "5.30",
    "numericValue": 5.3,
    "unit": "10^3/µL",
    "referenceRange": "4–11",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "كريات الدم الحمراء",
    "code": "rbc",
    "valueText": "2.78",
    "numericValue": 2.78,
    "unit": "10^6/µL",
    "referenceRange": "4–5.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "متوسط حجم الكرية MCV",
    "code": "mcv",
    "valueText": "102",
    "numericValue": 102,
    "unit": "fL",
    "referenceRange": "80–96",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "متوسط هيموغلوبين الكرية MCH",
    "code": "mch",
    "valueText": "36.5",
    "numericValue": 36.5,
    "unit": "pg",
    "referenceRange": "26–32",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الكيمياء الحيوية",
    "label": "إنزيم ALT (SGPT)",
    "code": "alt_u_l",
    "valueText": "22.00",
    "numericValue": 22,
    "unit": "U/L",
    "referenceRange": "0–55",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الكيمياء الحيوية",
    "label": "البيليروبين الكلي",
    "code": "bilirubin_total_umol_l",
    "valueText": "15.70",
    "numericValue": 15.7,
    "unit": "µmol/L",
    "referenceRange": "5.1–20.5",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-02-01",
    "department": "أمراض الدم والأورام",
    "category": "الكيمياء الحيوية",
    "label": "الكرياتينين",
    "code": "creatinine_umol_l",
    "valueText": "71.00",
    "numericValue": 71,
    "unit": "µmol/L",
    "referenceRange": "50.40–98.1",
    "status": "reassuring",
    "note": "وحدة القياس في هذا التقرير تختلف عن بعض التقارير الأحدث، لذلك لا تُجمع المقارنات بين الوحدات المختلفة.",
    "visitNumber": "hist-20220201-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS08155022.pdf",
    "reportDate": "2022-02-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الصفائح الدموية",
    "code": "platelets",
    "valueText": "139",
    "numericValue": 139,
    "unit": "10^3/µL",
    "referenceRange": "140–400",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الهيماتوكريت",
    "code": "hematocrit",
    "valueText": "32.2",
    "numericValue": 32.2,
    "unit": "%",
    "referenceRange": "35–48",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الهيموغلوبين",
    "code": "hemoglobin",
    "valueText": "11.0",
    "numericValue": 11,
    "unit": "g/dL",
    "referenceRange": "11–16",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "تباين حجم الكريات RDW",
    "code": "rdw",
    "valueText": "13.8",
    "numericValue": 13.8,
    "unit": "%",
    "referenceRange": "11.5–16.5",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "تركيز هيموغلوبين الكرية MCHC",
    "code": "mchc",
    "valueText": "34.2",
    "numericValue": 34.2,
    "unit": "g/dL",
    "referenceRange": "32–36",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "كريات الدم البيضاء",
    "code": "wbc",
    "valueText": "5.66",
    "numericValue": 5.66,
    "unit": "10^3/µL",
    "referenceRange": "4–11",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "كريات الدم الحمراء",
    "code": "rbc",
    "valueText": "3.05",
    "numericValue": 3.05,
    "unit": "10^6/µL",
    "referenceRange": "4–5.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "متوسط حجم الكرية MCV",
    "code": "mcv",
    "valueText": "106",
    "numericValue": 106,
    "unit": "fL",
    "referenceRange": "80–96",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "متوسط هيموغلوبين الكرية MCH",
    "code": "mch",
    "valueText": "36.1",
    "numericValue": 36.1,
    "unit": "pg",
    "referenceRange": "26–32",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الكيمياء الحيوية",
    "label": "إنزيم ALT (SGPT)",
    "code": "alt_u_l",
    "valueText": "24.00",
    "numericValue": 24,
    "unit": "U/L",
    "referenceRange": "0–55",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الكيمياء الحيوية",
    "label": "البيليروبين الكلي",
    "code": "bilirubin_total_umol_l",
    "valueText": "12.50",
    "numericValue": 12.5,
    "unit": "µmol/L",
    "referenceRange": "5.1–20.5",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-03-01",
    "department": "أمراض الدم والأورام",
    "category": "الكيمياء الحيوية",
    "label": "الكرياتينين",
    "code": "creatinine_umol_l",
    "valueText": "74.00",
    "numericValue": 74,
    "unit": "µmol/L",
    "referenceRange": "50.40–98.1",
    "status": "reassuring",
    "note": "وحدة القياس في هذا التقرير تختلف عن بعض التقارير الأحدث، لذلك لا تُجمع المقارنات بين الوحدات المختلفة.",
    "visitNumber": "hist-20220301-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS14282522(1).pdf",
    "reportDate": "2022-03-01",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الصفائح الدموية",
    "code": "platelets",
    "valueText": "184",
    "numericValue": 184,
    "unit": "10^3/µL",
    "referenceRange": "140–400",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الهيماتوكريت",
    "code": "hematocrit",
    "valueText": "35.6",
    "numericValue": 35.6,
    "unit": "%",
    "referenceRange": "35–48",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "الهيموغلوبين",
    "code": "hemoglobin",
    "valueText": "12.1",
    "numericValue": 12.1,
    "unit": "g/dL",
    "referenceRange": "11–16",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "تباين حجم الكريات RDW",
    "code": "rdw",
    "valueText": "12.6",
    "numericValue": 12.6,
    "unit": "%",
    "referenceRange": "11.5–16.5",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "تركيز هيموغلوبين الكرية MCHC",
    "code": "mchc",
    "valueText": "33.9",
    "numericValue": 33.9,
    "unit": "g/dL",
    "referenceRange": "32–36",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "كريات الدم البيضاء",
    "code": "wbc",
    "valueText": "4.53",
    "numericValue": 4.53,
    "unit": "10^3/µL",
    "referenceRange": "4–11",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "كريات الدم الحمراء",
    "code": "rbc",
    "valueText": "3.42",
    "numericValue": 3.42,
    "unit": "10^6/µL",
    "referenceRange": "4–5.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "متوسط حجم الكرية MCV",
    "code": "mcv",
    "valueText": "104",
    "numericValue": 104,
    "unit": "fL",
    "referenceRange": "80–96",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الدم",
    "label": "متوسط هيموغلوبين الكرية MCH",
    "code": "mch",
    "valueText": "35.3",
    "numericValue": 35.3,
    "unit": "pg",
    "referenceRange": "26–32",
    "status": "follow_up",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الكيمياء الحيوية",
    "label": "إنزيم ALT (SGPT)",
    "code": "alt_u_l",
    "valueText": "18.00",
    "numericValue": 18,
    "unit": "U/L",
    "referenceRange": "0–55",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "الكيمياء الحيوية",
    "label": "البيليروبين الكلي",
    "code": "bilirubin_total_umol_l",
    "valueText": "10.10",
    "numericValue": 10.1,
    "unit": "µmol/L",
    "referenceRange": "5.1–20.5",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2022-04-05",
    "department": "أمراض الدم والأورام",
    "category": "مؤشرات ورمية",
    "label": "مستضد سرطاني مضغي CEA",
    "code": "cea",
    "valueText": "2.19",
    "numericValue": 2.19,
    "unit": "ng/mL",
    "referenceRange": "غير المدخن: أقل من 5.0",
    "status": "reassuring",
    "note": null,
    "visitNumber": "hist-20220405-lab",
    "physician": "د. أحمد إبراهيم عنتر",
    "facility": "غير مذكورة في التقرير",
    "source": "LabReport-CS21376722.pdf",
    "reportDate": "2022-04-06",
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "البول",
    "label": "كريات الدم البيضاء في البول",
    "code": "urine_wbc",
    "valueText": "2–3 /HPF",
    "numericValue": null,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "reassuring",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "الحديد والالتهاب",
    "label": "الفيريتين",
    "code": "ferritin",
    "valueText": "238.7",
    "numericValue": 238.7,
    "unit": null,
    "referenceRange": "13–150",
    "status": "follow_up",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيماتوكريت",
    "code": "hematocrit",
    "valueText": "36.0",
    "numericValue": 36,
    "unit": null,
    "referenceRange": "37–47",
    "status": "follow_up",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيموغلوبين",
    "code": "hemoglobin",
    "valueText": "12.0",
    "numericValue": 12,
    "unit": null,
    "referenceRange": "12–15",
    "status": "reassuring",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "كريات الدم الحمراء",
    "code": "rbc",
    "valueText": "4.16",
    "numericValue": 4.16,
    "unit": null,
    "referenceRange": "4.2–5.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الضار LDL",
    "code": "ldl",
    "valueText": "166",
    "numericValue": 166,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "follow_up",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الكلي",
    "code": "total_cholesterol",
    "valueText": "264.6",
    "numericValue": 264.6,
    "unit": null,
    "referenceRange": "0–200",
    "status": "follow_up",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "السكر",
    "label": "السكر التراكمي HbA1c",
    "code": "hba1c",
    "valueText": "5.2",
    "numericValue": 5.2,
    "unit": null,
    "referenceRange": "4.2–6.4",
    "status": "reassuring",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "الغدة الدرقية",
    "label": "TSH",
    "code": "tsh",
    "valueText": "3.9",
    "numericValue": 3.9,
    "unit": null,
    "referenceRange": "0.27–4.2",
    "status": "reassuring",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-02-18",
    "department": "الطب الباطني",
    "category": "الكلى",
    "label": "الكرياتينين",
    "code": "creatinine",
    "valueText": "0.84",
    "numericValue": 0.84,
    "unit": null,
    "referenceRange": "0.5–1.0",
    "status": "reassuring",
    "note": null,
    "visitNumber": "886261",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "البول",
    "label": "كريات الدم البيضاء في البول",
    "code": "urine_wbc",
    "valueText": "أكثر من أن تُعد",
    "numericValue": null,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الحديد والالتهاب",
    "label": "الفيريتين",
    "code": "ferritin",
    "valueText": "254",
    "numericValue": 254,
    "unit": null,
    "referenceRange": "13–150",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيماتوكريت",
    "code": "hematocrit",
    "valueText": "34.8",
    "numericValue": 34.8,
    "unit": null,
    "referenceRange": "37–47",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيموغلوبين",
    "code": "hemoglobin",
    "valueText": "12.0",
    "numericValue": 12,
    "unit": null,
    "referenceRange": "12–15",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "كريات الدم الحمراء",
    "code": "rbc",
    "valueText": "4.05",
    "numericValue": 4.05,
    "unit": null,
    "referenceRange": "4.2–5.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الضار LDL",
    "code": "ldl",
    "valueText": "168",
    "numericValue": 168,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الكلي",
    "code": "total_cholesterol",
    "valueText": "265.5",
    "numericValue": 265.5,
    "unit": null,
    "referenceRange": "0–200",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "السكر",
    "label": "السكر التراكمي HbA1c",
    "code": "hba1c",
    "valueText": "5.2",
    "numericValue": 5.2,
    "unit": null,
    "referenceRange": "4.2–6.4",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الغدة الدرقية",
    "label": "TSH",
    "code": "tsh",
    "valueText": "4.74",
    "numericValue": 4.74,
    "unit": null,
    "referenceRange": "0.27–4.2",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الفيتامينات والمعادن",
    "label": "فيتامين B12",
    "code": "vitamin_b12",
    "valueText": "351.2",
    "numericValue": 351.2,
    "unit": null,
    "referenceRange": "145–569",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الفيتامينات والمعادن",
    "label": "فيتامين D (25-OH)",
    "code": "vitamin_d",
    "valueText": "41.27",
    "numericValue": 41.27,
    "unit": null,
    "referenceRange": "30–75",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الكلى",
    "label": "الكرياتينين",
    "code": "creatinine",
    "valueText": "1.01",
    "numericValue": 1.01,
    "unit": null,
    "referenceRange": "0.5–1.0",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-08-23",
    "department": "الطب الباطني",
    "category": "الكلى",
    "label": "اليوريا",
    "code": "urea",
    "valueText": "56.1",
    "numericValue": 56.1,
    "unit": null,
    "referenceRange": "16–49",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1119691",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "البول",
    "label": "كريات الدم البيضاء في البول",
    "code": "urine_wbc",
    "valueText": "6–8 /HPF",
    "numericValue": null,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الحديد والالتهاب",
    "label": "الفيريتين",
    "code": "ferritin",
    "valueText": "237.8",
    "numericValue": 237.8,
    "unit": null,
    "referenceRange": "13–150",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيماتوكريت",
    "code": "hematocrit",
    "valueText": "34.0",
    "numericValue": 34,
    "unit": null,
    "referenceRange": "37–47",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيموغلوبين",
    "code": "hemoglobin",
    "valueText": "11.8",
    "numericValue": 11.8,
    "unit": null,
    "referenceRange": "12–15",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "كريات الدم الحمراء",
    "code": "rbc",
    "valueText": "3.99",
    "numericValue": 3.99,
    "unit": null,
    "referenceRange": "4.2–5.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الضار LDL",
    "code": "ldl",
    "valueText": "165",
    "numericValue": 165,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الكلي",
    "code": "total_cholesterol",
    "valueText": "263.8",
    "numericValue": 263.8,
    "unit": null,
    "referenceRange": "0–200",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "السكر",
    "label": "السكر التراكمي HbA1c",
    "code": "hba1c",
    "valueText": "5.2",
    "numericValue": 5.2,
    "unit": null,
    "referenceRange": "4.2–6.4",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الغدة الدرقية",
    "label": "TSH",
    "code": "tsh",
    "valueText": "2.46",
    "numericValue": 2.46,
    "unit": null,
    "referenceRange": "0.27–4.2",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الفيتامينات والمعادن",
    "label": "فيتامين B12",
    "code": "vitamin_b12",
    "valueText": "448.5",
    "numericValue": 448.5,
    "unit": null,
    "referenceRange": "145–569",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الفيتامينات والمعادن",
    "label": "فيتامين D (25-OH)",
    "code": "vitamin_d",
    "valueText": "60.59",
    "numericValue": 60.59,
    "unit": null,
    "referenceRange": "30–75",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الكلى",
    "label": "الكرياتينين",
    "code": "creatinine",
    "valueText": "0.93",
    "numericValue": 0.93,
    "unit": null,
    "referenceRange": "0.5–1.0",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2025-11-18",
    "department": "الطب الباطني",
    "category": "الكلى",
    "label": "اليوريا",
    "code": "urea",
    "valueText": "44.9",
    "numericValue": 44.9,
    "unit": null,
    "referenceRange": "16–49",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1251269",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "البول",
    "label": "كريات الدم البيضاء في البول",
    "code": "urine_wbc",
    "valueText": "8–10 /HPF",
    "numericValue": null,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الحديد والالتهاب",
    "label": "الفيريتين",
    "code": "ferritin",
    "valueText": "220",
    "numericValue": 220,
    "unit": null,
    "referenceRange": "13–150",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيماتوكريت",
    "code": "hematocrit",
    "valueText": "33.2",
    "numericValue": 33.2,
    "unit": null,
    "referenceRange": "37–47",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيموغلوبين",
    "code": "hemoglobin",
    "valueText": "11.7",
    "numericValue": 11.7,
    "unit": null,
    "referenceRange": "12–15",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "كريات الدم الحمراء",
    "code": "rbc",
    "valueText": "3.91",
    "numericValue": 3.91,
    "unit": null,
    "referenceRange": "4.2–5.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الضار LDL",
    "code": "ldl",
    "valueText": "58",
    "numericValue": 58,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الكلي",
    "code": "total_cholesterol",
    "valueText": "149.6",
    "numericValue": 149.6,
    "unit": null,
    "referenceRange": "0–200",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "السكر",
    "label": "السكر التراكمي HbA1c",
    "code": "hba1c",
    "valueText": "5.2",
    "numericValue": 5.2,
    "unit": null,
    "referenceRange": "4.2–6.4",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الغدة الدرقية",
    "label": "T3 الكلي",
    "code": "total_t3",
    "valueText": "1.26",
    "numericValue": 1.26,
    "unit": null,
    "referenceRange": "1.3–3.1",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الغدة الدرقية",
    "label": "TSH",
    "code": "tsh",
    "valueText": "3.88",
    "numericValue": 3.88,
    "unit": null,
    "referenceRange": "0.27–4.2",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-02-22",
    "department": "الطب الباطني",
    "category": "الفيتامينات والمعادن",
    "label": "فيتامين B12",
    "code": "vitamin_b12",
    "valueText": "288.1",
    "numericValue": 288.1,
    "unit": null,
    "referenceRange": "145–569",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1380027",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "البروتينات",
    "label": "الغلوبولين",
    "code": "globulin",
    "valueText": "2.22",
    "numericValue": 2.22,
    "unit": null,
    "referenceRange": "2.5–3.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الحديد والالتهاب",
    "label": "الفيريتين",
    "code": "ferritin",
    "valueText": "206.6",
    "numericValue": 206.6,
    "unit": null,
    "referenceRange": "13–150",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيماتوكريت",
    "code": "hematocrit",
    "valueText": "32.3",
    "numericValue": 32.3,
    "unit": null,
    "referenceRange": "37–47",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "الهيموغلوبين",
    "code": "hemoglobin",
    "valueText": "11.1",
    "numericValue": 11.1,
    "unit": null,
    "referenceRange": "12–15",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الدم",
    "label": "كريات الدم الحمراء",
    "code": "rbc",
    "valueText": "3.75",
    "numericValue": 3.75,
    "unit": null,
    "referenceRange": "4.2–5.4",
    "status": "follow_up",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الضار LDL",
    "code": "ldl",
    "valueText": "78",
    "numericValue": 78,
    "unit": null,
    "referenceRange": "غير مذكور",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الدهون",
    "label": "الكوليسترول الكلي",
    "code": "total_cholesterol",
    "valueText": "164.7",
    "numericValue": 164.7,
    "unit": null,
    "referenceRange": "0–200",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الغدة الدرقية",
    "label": "TSH",
    "code": "tsh",
    "valueText": "2.7",
    "numericValue": 2.7,
    "unit": null,
    "referenceRange": "0.27–4.2",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الفيتامينات والمعادن",
    "label": "فيتامين B12",
    "code": "vitamin_b12",
    "valueText": "500.5",
    "numericValue": 500.5,
    "unit": null,
    "referenceRange": "145–569",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  },
  {
    "examDate": "2026-05-31",
    "department": "الطب الباطني",
    "category": "الفيتامينات والمعادن",
    "label": "فيتامين D (25-OH)",
    "code": "vitamin_d",
    "valueText": "34.94",
    "numericValue": 34.94,
    "unit": null,
    "referenceRange": "30–75",
    "status": "reassuring",
    "note": null,
    "visitNumber": "1495995",
    "physician": "د. ضياء عكاد",
    "facility": "غير مذكورة في التقرير",
    "source": "مختبر مستشفى المملكة",
    "reportDate": null,
    "reportType": "تحاليل مختبرية"
  }
] as const;
